### ISSUE TITLE
Initializers are not allowed in ambient contexts.

### ISSUE THREAD

**Issue by ilyshkafeed** [DanielYKPan/date-time-picker#517]
https://github.com/DanielYKPan/date-time-picker/blob/1bf339f6555e31673d371e416723a10177f933e4/src/date-time/adapter/date-time-adapter.class.ts#L33

https://github.com/DanielYKPan/date-time-picker/blob/1bf339f6555e31673d371e416723a10177f933e4/src/date-time/adapter/date-time-adapter.class.ts#L36

ERROR in node_modules/ng-pick-datetime/date-time/adapter/date-time-adapter.class.d.ts(13,44): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ng-pick-datetime/date-time/adapter/date-time-adapter.class.d.ts(14,46): error TS1039: Initializers are not allowed in ambient contexts.

**Comment by ilyshkafeed** [comment]
Ok. updated the typescript and everything will be fine.

**Comment by andiramuttakim** [comment]
> Updated to typescript version 2.9.2, issue still persists.

try using version 6.0.16, it works for me.

`npm install ng-pick-datetime@6.0.16`

**Comment by DanielYKPan** [comment]
ng-pick-datetime@7.*.* require typescript 3.1.*

**Comment by ankit18singh** [comment]
Same issue with datetime@6.0.16 and typescript v2.9.2

**Comment by zainkhwaja** [comment]
Also facing the same issue, somehow It worked for me before..
But when I ran npm start again the next day, it showed up again.

Not sure if it's something wrong with the TS version or of the library itself.

**Comment by AhmedSaulti** [comment]
@andiramuttakim  Thnx, that was the only solution that got it working for me.
I use angular 6 and updated typescript to 3.1.6, with the package @6.0.16

**Comment by bboyzplatform** [comment]
> 6.0.16

Thanks. It helps for Angular 6 project

**Comment by codeDelights** [comment]
> I use angular 6 and updated typescript to 3.1.6, with the package @6.0.16

Well. With angular 6 and ng-pick-datetime@6.0.16 it worked for me!

**Comment by shivam222** [comment]
Above solution worked for me as well.

**Comment by rohit-aneja** [comment]
`npm install ng-pick-datetime@6.0.16`
Worked for me also on Angular version 6

**Comment by quetzalcoatl** [comment]
When working on Angular 5 project, typescript 2.9.2, (yeah, all quite old, but no chances of updating for the next N months) with `ng-pick-datetime` 5.2.6 and `ng-pick-datetime-moment` 1.0.7, I've stumbled upon the same error:

> ERROR in node_modules/ng-pick-datetime/date-time/adapter/date-time-adapter.class.d.ts(13,44): error TS1039: Initializers are not allowed in ambient contexts.

Strangely, on some machines it compiled just fine, on others it failed with that error.

Eventually, it turned out that we've had in `package.json`

```
    "ng-pick-datetime": "^5.2.6",
    "ng-pick-datetime-moment": "^1.0.7",
```

On some machines, where the build started with a clean cache, the `npm install` was downloading `ng-pick-datetime-moment` at `1.0.8` version due to the `^` character in the `package.json`.

Those `package.json` lines were added automatically when one of the developers used `npm install ng-pick-datetime@5.2.6` and `npm install ng-pick-datetime-moment@1.0.7`. The problem was actually discovered only when the code reached CI/CD pipeline. The problem was not discovered immediatelly, because at developer's machine the packages were already in cache, and CI/CD workers started with clean state with no cache and those machines picked `1.0.8` as the best match for `^1.0.7`.

The `1.0.8` moment package is not compatible with Angular 5 with TS 2.9.2.
That package is meant for Angular 6+ and `ng-pick-datetime` >= 6.0, that's why even the developer started with installing `@1.0.7`.

Changing `package.json` entries resolved the problem:
```
    "ng-pick-datetime": "5.2.6",
    "ng-pick-datetime-moment": "1.0.7",
```

While that was pretty basic overlook, and while we knew that these exact package versions were required, and those packages should never have a `^` there, then I suppose that having a package `1.0.7` dedicated to Angular 5 and releasing an incompatible version dedicated to Angular 6+ as a "patch update" `1.0.8` wasn't really a good idea either.. HTH!

**Comment by fitrailham** [comment]
thank. it help my project @andiramuttakim

**Comment by vanmathisiva** [comment]
> > Updated to typescript version 2.9.2, issue still persists.
> 
> try using version 6.0.16, it works for me.
> 
> `npm install ng-pick-datetime@6.0.16`

yes its working

**Comment by TranDuyLong8119** [comment]
> When working on Angular 5 project, typescript 2.9.2, (yeah, all quite old, but no chances of updating for the next N months) with `ng-pick-datetime` 5.2.6 and `ng-pick-datetime-moment` 1.0.7, I've stumbled upon the same error:
> 
> > ERROR in node_modules/ng-pick-datetime/date-time/adapter/date-time-adapter.class.d.ts(13,44): error TS1039: Initializers are not allowed in ambient contexts.
> 
> Strangely, on some machines it compiled just fine, on others it failed with that error.
> 
> Eventually, it turned out that we've had in `package.json`
> 
> ```
>     "ng-pick-datetime": "^5.2.6",
>     "ng-pick-datetime-moment": "^1.0.7",
> ```
> 
> On some machines, where the build started with a clean cache, the `npm install` was downloading `ng-pick-datetime-moment` at `1.0.8` version due to the `^` character in the `package.json`.
> 
> Those `package.json` lines were added automatically when one of the developers used `npm install ng-pick-datetime@5.2.6` and `npm install ng-pick-datetime-moment@1.0.7`. The problem was actually discovered only when the code reached CI/CD pipeline. The problem was not discovered immediatelly, because at developer's machine the packages were already in cache, and CI/CD workers started with clean state with no cache and those machines picked `1.0.8` as the best match for `^1.0.7`.
> 
> The `1.0.8` moment package is not compatible with Angular 5 with TS 2.9.2.
> That package is meant for Angular 6+ and `ng-pick-datetime` >= 6.0, that's why even the developer started with installing `@1.0.7`.
> 
> Changing `package.json` entries resolved the problem:
> 
> ```
>     "ng-pick-datetime": "5.2.6",
>     "ng-pick-datetime-moment": "1.0.7",
> ```
> 
> While that was pretty basic overlook, and while we knew that these exact package versions were required, and those packages should never have a `^` there, then I suppose that having a package `1.0.7` dedicated to Angular 5 and releasing an incompatible version dedicated to Angular 6+ as a "patch update" `1.0.8` wasn't really a good idea either.. That totally should be a `2.0.0` package in the first place!
> 
> Hope this helps people who are still working with ng5.

thank you! it worked like a charm
