### ISSUE TITLE
Cannot set property 'picker' of undefined

### ISSUE THREAD

**Issue by anderserikpersson** [DanielYKPan/date-time-picker#457]
preview-fe7237b13d780dbf847da.js:1 ERROR TypeError: Cannot set property 'picker' of undefined
    at n.open (picker.bundle.js:1)
    at e.handleClickOnHost (picker.bundle.js:1)
    at Object.eval [as handleEvent] (VM425 AppComponent.ngfactory.js:13)
    at handleEvent (view.ts:138)
    at callWithDebugContext (services.ts:639)
    at Object.debugHandleEvent [as handleEvent] (services.ts:375)
    at dispatchEvent (util.ts:134)
    at eval (element.ts:195)
    at HTMLInputElement.eval (dom_renderer.ts:52)
    at ZoneDelegate.invokeTask (zone.js:421)

Doesn't work with Angular 6.0.0. Works with Angular 6.1.3.

https://stackblitz.com/edit/angular60-ng-pick-datetime
https://stackblitz.com/edit/angular61-ng-pick-datetime

**Comment by DanielYKPan** [comment]
Then update you angular version to +6.1

**Comment by macin40** [comment]
> preview-fe7237b13d780dbf847da.js:1 ERROR TypeError: Cannot set property 'picker' of undefined
> at n.open (picker.bundle.js:1)
> at e.handleClickOnHost (picker.bundle.js:1)
> at Object.eval [as handleEvent] (VM425 AppComponent.ngfactory.js:13)
> at handleEvent (view.ts:138)
> at callWithDebugContext (services.ts:639)
> at Object.debugHandleEvent [as handleEvent] (services.ts:375)
> at dispatchEvent (util.ts:134)
> at eval (element.ts:195)
> at HTMLInputElement.eval (dom_renderer.ts:52)
> at ZoneDelegate.invokeTask (zone.js:421)
> 
> Doesn't work with Angular 6.0.0. Works with Angular 6.1.3.
> 
> https://stackblitz.com/edit/angular60-ng-pick-datetime
> https://stackblitz.com/edit/angular61-ng-pick-datetime

You can fix this by importing `BrowserAnimationsModule`.

**Comment by maksof-Hussain** [comment]
i am facing the same issue and my angular version is 10+ and i have also imported BrowserAnimationsModule.

**Comment by ArtzGroup** [comment]
Even I am having the issue. I am getting this error when I tried to use inline. Remaining works completely fine except inline.
`cannot set property 'picker' of undefined`

**Comment by kartikchandra14** [comment]
@DanielYKPan please check it is creating me to remove the library.
Although i planned my project by using your calender.

Please Sort it Out ASAP because "inline date picker" is not working with ANGULAR 9,10,11 versions.

May be due to involvement of Ivy.
PLEASE reply me ASAP if you solve this isse.

I have to use inline calendar. Although simple date-picker work well with all version.
I hope you reply soon.

FROM
KARTIK (MEAN SDE)
chandra.kartik01@gmail.com
