### ISSUE TITLE
Not working @danielmoncada/angular-datetime-picker after upgrading package from version 12.2.0 to 14.1.1

### ISSUE THREAD

**Issue by eapatel** [DanielYKPan/date-time-picker#770]
I upgraded package version from 12.2.0 to 14.1.1 and now nothing is working as it was working with version 12.2.0.

The output looks like below on the browser when I click on input to open calendar
![image](https://user-images.githubusercontent.com/47823148/185260611-ae08e480-dd9f-4e91-a3b1-1390841c67a5.png)

Also getting this error **e.format is not a function**  in the browser console.

Please provide solution to resolve this issue.

**Comment by eapatel** [comment]
I fixed the issue so closing it.
