### ISSUE TITLE
 Cannot find module '@angular/cdk/overlay'.

### ISSUE THREAD

**Issue by jayrajmishra** [DanielYKPan/date-time-picker#523]
Package which I have Installed - npm install ng-pick-datetime@6.0.16 --save

I have used Angular 6.1.9 and while using ng server it's throwing error.

ERROR in node_modules/ng-pick-datetime/date-time/date-time-picker.component.d.ts(2,62): error TS2307: Cannot find module '@angular/cdk/overlay'.
node_modules/ng-pick-datetime/dialog/dialog-config.class.d.ts(2,32): error TS2307: Cannot find module '@angular/cdk/overlay'.
node_modules/ng-pick-datetime/dialog/dialog-container.component.d.ts(3,34): error TS2307: Cannot find module '@angular/cdk/a11y'.
node_modules/ng-pick-datetime/dialog/dialog-container.component.d.ts(4,84): error TS2307: Cannot find module '@angular/cdk/portal'.
node_modules/ng-pick-datetime/dialog/dialog-ref.class.d.ts(2,28): error TS2307: Cannot find module '@angular/cdk/overlay'.
node_modules/ng-pick-datetime/dialog/dialog.service.d.ts(6,59): error TS2307: Cannot find module '@angular/cdk/overlay'.node_modules/ng-pick-datetime/dialog/dialog.service.d.ts(7,31): error TS2307: Cannot find module '@angular/cdk/portal'.

**Comment by lialosiu** [comment]
npm install @angular/cdk@^6.3.0

**Comment by BaamAadmi** [comment]
I had the exact same issue, to fix it I upgraded to Angular 7.0.0 and TS 3.1.6. But still did not work. So, I did
> npm install @angular/cdk@^6.3.0   

And this did the trick for me.  Thanks @lialosiu

**Comment by ermarkar** [comment]
On documentation it shows no extra dependencies, please update these dependent modules as well.. It is showing to install

@angular/cdk/overlay
@angular/cdk/portal

**Comment by canbax** [comment]
this must be added as dependency or it should be noted inside readme

**Comment by suhailkc** [comment]
@ermarkar I have the same issue.

Is there any solution for that?

**Comment by roland-jungwirth** [comment]
`npm install @angular/cdk`

worked on my side - installs version ^8.2.3 as of today.
